name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  specs:
    runs-on: ubuntu-latest
    name: Specs (Ruby ${{ matrix.ruby }})
    strategy:
      matrix:
        ruby:
          - '3.2'
          - '3.3'
          - '3.4'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run specs
      run: bundle exec rspec
    - name: Run RuboCop
      run: bundle exec rubocop
